### PR TITLE
Only return patterns that have a semantic

### PR DESCRIPTION
**Pull request by prep**
I've made some changes that makes this package behave a bit more like logstash, in that it now only returns patterns that have a semantic from the Grok.Parse() and Grok.ParseToMultiMap() functions. 

For instance, where your example code used to return:

```
       response: 404
          bytes: 207
               : 207
       HOSTNAME: 127.0.0.1
       USERNAME: -
       MONTHDAY: 23
        request: /index.php
      BASE10NUM: 207
           IPV6: 
           auth: -
      timestamp: 23/Apr/2014:22:58:32 +0200
           verb: GET
    httpversion: 1.1
           TIME: 22:58:32
           HOUR: 22
COMMONAPACHELOG: 127.0.0.1 - - [23/Apr/2014:22:58:32 +0200] "GET /index.php HTTP/1.1" 404 207
       clientip: 127.0.0.1
             IP: 
          ident: -
          MONTH: Apr
           YEAR: 2014
         SECOND: 32
            INT: +0200
           IPV4: 
         MINUTE: 58
     rawrequest: 
```

It now returns:

```
       response: 404
          bytes: 207
        request: /index.php
           auth: -
      timestamp: 23/Apr/2014:22:58:32 +0200
           verb: GET
    httpversion: 1.1
       clientip: 127.0.0.1
          ident: -
     rawrequest:
```

### CODE REVIEW

**Comment by prep** [comment]
It should be noted that I've not changed the patterns.go file, so you'll only see the effects of these changes when you overwrite the default patterns

```go
g := grok.New()
g.AddPatternsFromPath("patterns/")

// g.Parse(...)
```

**Comment by vjeantet** [comment]
Hi @prep, thanks for this large PR :)

I'll not merge your PR as it is, because it can introduce some regression, I'll modify it a little bit to see named group only parsing as an optional behavior.

I think that Parse() and MultiParse func need to accept a param like a namedCapturesOnly bool.

What do you think ?

**Comment by fxnn** [comment]
From a code readability perspective,

```
grok.ParseOnlyNamedCaptures(string)
```

would be more favorable than

```
grok.Parse(string, true)
```

**Comment by vjeantet** [comment]
I agree with Felix.

**Comment by vjeantet** [comment]
issue #5 opened

**Comment by prep** [comment]
I have to disagree, although between the 2 options Felix's suggestion is the most favourable :-)

If you're advertising this as a grok package, doesn't it make sense to mimic logstash's grok behaviour (http://logstash.net/docs/1.4.2/filters/grok)? At least, that's what I was aiming for with this PR.

What's the argument for keeping the old behaviour in?

**Comment by vjeantet** [comment]
When i use the grok debugger https://grokdebug.herokuapp.com, and parse an apache line it returns a full map of values, then if i check "Named Capture Only" it will returns only the expected ouput.

According to the logstash's documentation, each behavior is available, but Logstash use the grok tool with a default_option *named_captures_only* set to true.

Data to test the grok debugger

INPUT
```
127.0.0.1 - - [23/Apr/2014:22:58:32 +0200] "GET /index.php HTTP/1.1" 404 207
```

FILTER
```
%{COMMONAPACHELOG}
```

**Comment by prep** [comment]
Ah, thanks for that info! Now it makes sense :-)

If I may make another suggestion to Felix and yourself. What about this?

```go
type Options struct {
	NamedCapturesOnly bool
}

// Grok Type
type Grok struct {
	compiledPattern map[string]*regexp.Regexp
	patterns        map[string]string
	options         *Options
	serviceMu       sync.Mutex
}

// New returns a Grok struct
func New() *Grok {
	return NewWithOptions(&Options{})
}

func NewWithOptions(options *Options) *Grok {
	g := new(Grok)
	g.patterns = patterns
	g.compiledPattern = map[string]*regexp.Regexp{}
	g.options = options
	return g
}

// [changes to denormalizePattern() that checks NamedCapturesOnly]
```

That way the old behaviour is the default when you call New(), but you get some toggles to play with by using NewWithOptions(). This makes extending Grok with new options easier. For instance, I can think of an option that doesn't make NewWithOptions() load the patterns from patterns.go.

**Comment by fxnn** [comment]
I agree with @prep, an option would really make sense for the end user.

(Btw. -- I didn't read the code, but isn't it so that `Parse()` and `ParseOnlyNamedCaptures()` wouldn't coexist well, because they need the patterns compiled differently? And so, they would need different pattern caches?)

**Comment by prep** [comment]
@fxxn you're right. The compiled-in patterns do need 2 versions for my example to work.

**Comment by prep** [comment]
So it would look more like:

```go
func NewWithOptions(options *Options) *Grok {
	g := &Grok{compiledPatterns: map[string]*regexp.Regexp{}, options: options}
	if options.NamedCapturesOnly {
		g.patterns = namedCapturesOnlyPatterns
	} else {
		g.patterns = patterns
	}

	return g
}
```

**Comment by vjeantet** [comment]
Hello,
  Using an option bag is the way to go.
  Yes, 2 distinct compiled-in patterns cache should be written : a new file patternsnc.go will be added.
  Only one will be used, depending on Options used.

I'll start working on this and will propose you an implementation.

**Pull request closed without merging**
